### ISSUE TITLE
[back] graphql impact

### ISSUE THREAD

**Issue by blacroix** [xebia-france/ximpact#3]

**Comment by jsmadja** [comment]
mutation {
    impact_create(description: "Etre rapide", xebianId: "{{xebianId}}", customerId: "{{customerId}}") {
        id
        description
        xebian {
            id
            email
            created_at
            updated_at
            firstname
            lastname
        }
        customer {
            id
            email
            created_at
            updated_at
            firstname
            lastname
            company
        }
    }
}
